name: Docker
on: [push]
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: recursive
          token: ${{ secrets.CI_TOKEN }}

      - name: Login to Docker Hub
        run: echo $DOCKER_PASSWORD | docker login --username $DOCKER_USERNAME --password-stdin
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Machine Manager
        run: docker build . -t cartesi/machine-manager
      
      - name: Build Mock Server
        run: docker build . -t cartesi/machine-manager-mock -f DockerfileMock

      - name: Push to Docker Hub
        run: |
          docker tag cartesi/machine-manager cartesi/machine-manager:${GITHUB_REF:11}
          docker tag cartesi/machine-manager-mock cartesi/machine-manager-mock:${GITHUB_REF:11}
          docker push cartesi/machine-manager
          docker push cartesi/machine-manager:${GITHUB_REF:11}
          docker push cartesi/machine-manager-mock
          docker push cartesi/machine-manager-mock:${GITHUB_REF:11}
        if: startsWith(github.ref, 'refs/tags/v')
