name: Docker
on: [push]
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          token: ${{ secrets.CI_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: cartesi/machine-manager
          tag-semver: |
            {{version}}

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push docker image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          push: true
          load: true
          tags: ${{ steps.docker_meta.outputs.tags }}
          secrets: |
            GIT_AUTH_TOKEN=${{ secrets.CI_TOKEN }}

      - name: Test
        run: |
          docker run --rm --name cartesi_mm_container -p 50051:50051 -v $(pwd)/test-files:/root/host cartesi/machine-manager & timeout 20 bash -c 'while ! nc -q0 127.0.0.1 50051 < /dev/null > /dev/null 2>&1; do sleep 1; done' && ./test-client -c && echo "tests succeeded" && docker kill cartesi_mm_container
